name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  linux-cross-win32:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.14.3"
      MESON_VERSION: "1.10.1"

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 file

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install Python
        run: uv python install "${PYTHON_VERSION}"

      - name: Configure
        run: >-
          uv tool run --python "${PYTHON_VERSION}" --from "meson==${MESON_VERSION}" --with ninja
          meson setup --cross-file meson/cross/mingw32.ini --buildtype release
          .meson/build/mingw-win32-linux

      - name: Build
        run: >-
          uv tool run --python "${PYTHON_VERSION}" --from "meson==${MESON_VERSION}" --with ninja
          meson compile -C .meson/build/mingw-win32-linux

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        if: ${{ env.ACT != 'true' }}
        with:
          name: bitnessscan-win32
          path: build/
